baseURL = 'https://charming-chimera-14b53c.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'wdx1'
#theme = 'cai'


enableGitInfo = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"] # you will get a console error message without this

# [params]
#     theme = 'default'
#     sideMenuTheme = 'default'