[build]
    publish = "public"
    command = "./build.sh"

[context.production.environment]


[context.production.environment]
    HUGO_VERSION = "0.93.3"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.93.3"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.93.3"